name: Publish Nuget

on:
  push:
    tags: 'v*.*.*'

jobs:
  pack:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore tools
      run: dotnet tool restore
    - name: Verify code format
      run: dotnet dotnet-format --check
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --no-build --configuration Release
    - name: Determine version from tag
      run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=${env.VERSION:1}
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifacts
        path: ./artifacts
    - name: Publish nuget to AppVeyor nuget registry
      run: dotnet nuget push ./artifacts/*.nupkg --skip-duplicate --api-key ${{secrets.APPVEYOR_NUGET_API_KEY}} --source 'https://ci.appveyor.com/nuget/makingsense-aspnet/api/v2/package'
    - name: Publish nuget to to GitHub registry
      run: dotnet nuget push ./artifacts/*.nupkg --skip-duplicate --api-key ${{secrets.GITHUB_NUGET_API_KEY}} --source 'https://nuget.pkg.github.com/FromDoppler/index.json'
